### ISSUE TITLE
No longer working in Chrome 96.0.4664.93

### ISSUE THREAD

**Issue by JT114881** [rbika/easy-purple-incognito-theme#5]
This no longer works in Chrome 96.0.4664.93
The window color for Incognito is not affected by this addon at all.

**Comment by JT114881** [comment]
> This no longer works in Chrome 96.0.4664.93 The window color for Incognito is not affected by this addon at all.

Workaround is to disable 'Enable Incognito brand consistency in desktop.' in chrome://flags/

**Comment by munkychop** [comment]
The 'Enable Incognito brand consistency in desktop.' flag doesn't seem to exist anymore and this theme is still broken, as of Chrome 104.0.5112.101.

@rbika would you be able to take a look?

**Comment by rbika** [comment]
Hey @munkychop, unfortunately, this theme no longer works as Google has blocked all official capabilities to theme the Incognito window. I'm archiving this repo, for now, maybe we'll have a new way to customize incognito again in the future.

**Comment by munkychop** [comment]
Hey @rbika, thanks for the response. Yeah, it’s unfortunate. I actually experimented with creating a quick theme myself yesterday and came to the same conclusion.

I hope there’ll be a simple way to achieve this in the future.

FWIW, I decided to take the opposite approach and theme the non incognito mode, to make it slightly different from the incognito mode. Works for now 🙂

**Comment by rbika** [comment]
Nice workaround 😂. 

> I hope there’ll be a simple way to achieve this in the future.

Let's hope so. Pls, let et me know if you find anything about it.
